services:
  backend:
    build:
      context: .
      dockerfile: docker/php/dockerfile
    container_name: suport_backend
    working_dir: /var/www
    volumes:
      - ./api:/var/www
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
    command: php artisan serve --host=0.0.0.0 --port=8000

  frontend:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: suport_frontend
    volumes:
      - ./app:/app
    ports:
      - "9000:9000"
    depends_on:
      - backend
    
